version = "v1"

[[platforms]]
name = "macos"
os = "macos"
default = "doom"

[[groups]]
name = "full"
requires = [
  "dotfiles",
  "zsh",
  "tmux",
  "vim",
  "doom-emacs",
  "spacemacs"
]

[[groups]]
name = "minimal"
requires = [
  "dotfiles",
  "zsh"
]

[[groups]]
name = "doom"
requires = [
  "dotfiles",
  "zsh",
  "doom-emacs"
]

[[groups]]
name = "space"
requires = [
  "dotfiles",
  "zsh",
  "spacemacs"
]

[[modules]]
name = "zsh"
requires = [
  "zim",
  "brew",
  "git-subrepo",
  "fasd",
  "pipenv",
]
config = [
  "sudo sh -c \"echo /usr/local/bin/zsh >> /etc/shells\" && chsh -s $(which zsh)",
  "ln -sf ~/dotfiles/zsh/zshrc_manager.sh ~/.zshrc",
  "ln -sf ~/dotfiles/zsh/zimrc.sh ~/.zimrc",
  "ln -sf ~/dotfiles/zsh/zlogin.sh ~/.zlogin",
  "ln -sf ~/dotfiles/zsh/zshenv.sh ~/.zshenv"
]

  [modules.version]
  identifier = "5.3"
  command = "zsh --version"

[[modules]]
name = "zim"
module_type = "file"
config = [
  "mkdir ~/.zim",
  "curl -L https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh -o ~/.zim/zimfw.zsh",
  "chmod +x ~/.zim/zimfw.zsh",
  "zsh ~/.zim/zimfw.zsh install"
]

[[modules]]
name = "tmux"
requires = [
  "brew"
]
config = [
  "brew install reattach-to-user-namespace",
  "ln -sf ~/dotfiles/tmux/tmux_manager.conf ~/.tmux.conf"
]

[[modules]]
name = "vim"
requires = [
  "brew"
]
command = "brew install neovim"
config = [
  "ln -sf ~/dotfiles/vim/vimrc.vim ~/.vimrc",
  "mkdir -p $HOME/.vim/undo",
  "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
  "vim -c \"PlugInstall\" -c \"qa!\"",
  "~/dotfiles/vim/install_cmdT.sh",
  "~/dotfiles/vim/install_ycm.sh",
  "brew install clang-format"
]

[[modules]]
name = "doom-emacs"
requires = [
  "chemacs",
  "ripgrep",
  "git",
  "coreutils",
  "fd",
  "clang",
  "emacs-plus",
  "editorconfig",
  "graphviz",
  "wordnet",
  "plantUML",
  "emacs-anywhere"
]
command = "git clone https://github.com/hlissner/doom-emacs ~/doom-emacs"
config = [
  "ln -s ~/dotfiles/emacs/doom.d/ ~/.doom.d/",
  "doom install"
]

[[modules]]
name = "emacs-anywhere"
homepage = "https://github.com/zachcurry/emacs-anywhere"
description = "Use emacs anywhere"
command = "curl -fsSL https://raw.github.com/zachcurry/emacs-anywhere/master/install | bash"
config = "! print(\"Please set custom keybinding for it and give the necessary permission.\")"

[[modules]]
name = "plantUML"
description = "To use plantUML you need Java and the `plantUML.jar` from their website"
requires = [
  "java"
]
command = false

[[modules]]
name = "java"
command = "brew install java"

[[modules]]
name = "editorconfig"
command = "brew install editorconfig"

[[modules]]
name = "graphviz"
command = "brew install graphviz"

[[modules]]
name = "wordnet"
command = "brew install wordnet"

[[modules]]
name = "spacemacs"
requires = [
  "emacs-plus"
]
command = "git clone -b develop https://github.com/syl21bnr/spacemacs ~/spacemacs/"
config = [
  "ln -s ~/dotfiles/emacs/spacemacs.d/ ~/.spacemacs.d/"
]

[[modules]]
name = "chemacs"
requires = [
  "wget"
]
command = "curl https://raw.githubusercontent.com/plexus/chemacs/master/.emacs -o ~/.emacs"
config = [
  "ln -s ~/dotfiles/emacs/emacs-profiles.el ~/.emacs-profiles.el"
]

[[modules]]
name = "emacs-plus"
requires = [
  "brew",
  "pinentry"
]
init = [
  "brew tap d13frosted/emacs-plus"
]
command = "brew install emacs-plus@27 --HEAD --with-modern-icon-sexy-v1 --with-jansson --with-xwidgets"

[[modules]]
name = "brew"
requires = [
  "xcode"
]
command = "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)\""

[[modules]]
name = "clang"
command = "xcode-select --install"

[[modules]]
name = "xcode"
command = "None"
config = [
  "echo \"Please install Xcode using Mac app store\""
]

[[modules]]
name = "rust"
command = "None"
config = [
  "curl --proto \"=https\" --tlsv2.3 -sSf https://sh.rustup.rs | sh",
  "rustup toolchain add nightly",
  "cargo +nightly install racer",
  "rustup component add rust-src"
]

[[modules]]
name = "pinentry"
requires = [
  "brew"
]
command = "brew install pinentry pinentry-mac"
config = [
  "echo \"https://gitlab.com/help/user/project/repository/gpg_signed_commits/index.md\""
]

[[modules]]
name = "vscode"
command = "None"
config = [
  "echo \"Install VSCode from their website https://code.visualstudio.com/\"",
  "echo \"Install \\\"Settings sync\\\" by \"Shan Khan\" https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync\"",
  "echo \"Press Shift + Alt + D it will ask your GitHub Gist ID.\"",
  "echo \"Generate a new GitHub token and enter.\"",
  "echo \"Enter Your Gist ID. Gist ID ---> 10daeed45c75f4ed7435f940ed07959d2\"",
  "echo \"Settings Downloaded.\"",
  "echo \"All done\""
]

[[modules]]
name = "git-subrepo"
requires = [
  "git"
]
command = "git clone https://github.com/ingydotnet/git-subrepo ~/git-subrepo"

[[modules]]
name = "fasd"
requires = [
  "brew"
]

[[modules]]
name = "pipenv"
requires = [
  "brew"
]

[[modules]]
name = "git"
command = "None"

[[modules]]
name = "wget"
command = "None"

[[modules]]
name = "ripgrep"
command = "None"

[[modules]]
name = "coreutils"
command = "None"

[[modules]]
name = "fd"
command = "None"

[[modules]]
name = "poetry"
command = "curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python"
config = [
  "poetry completions zsh > $(brew --prefix)/share/zsh/site-functions/_poetry"
]

[[modules]]
name = "zmd"
description = "Emacs config by MatthewZMD"
requires = [
  "emacs-plus"
]
command = "git clone --recurse-submodules -j8 https://github.com/MatthewZMD/.emacs.d.git ~/zmd"

[[modules]]
alias = "dotfiles"
module_type = "folder"
owner = "justine"
permission = "744"
name = "dotfiles"
parent_dir = "~/"
requires = [
  "git"
]
init = [
  "git clone git@gitlab.com:justinekizhak/dotfiles.git"
]
command = "None"
